### ISSUE TITLE
Sort out RSD f.

### ISSUE THREAD

**Issue by slosar** [radiohep/CVFisher#1]
Shaw sets it to one, LiuPob goes through painful diff.

**Comment by jrs65** [comment]
I can change that pretty easily. I have a Pade approximant to it in `cora`, so I can just use that.

**Comment by slosar** [comment]
Not yet, this issue was really for my internal consumption, since I'm trying to get to the bottom of differences (which I'm unlikely to completely understand, but perhaps at least somewhat)... More soon.

**Comment by slosar** [comment]
Fixed.
